### ISSUE TITLE
Please provide license file

### ISSUE THREAD

**Issue by obo-spi** [react-component/virtual-list#85]

**Comment by bard83** [comment]
it would be great!

**Comment by bard83** [comment]
license mentioned here:  https://github.com/react-component/virtual-list/blob/a107a64c8cda4aee69aa3447ad8e77f5bd4085de/package.json#L28

**Comment by momesana** [comment]
Hi,

despite the fact that the license is listed in the package.json and also on the [NPM repository](https://www.npmjs.com/package/rc-virtual-list) it is always good practice to provide a dedicated LICENSE file. This is also very important for people like us that use a third-party tool (license-verifier) to automatically prevent license infringements and a costly litigation due to the use of third-party libraries with the wrong license. Almost all available license-checkers first look inside the License file and then inside the README file in order to find the license. These tools usually don't regard a mere `package.json` entry as sufficient enough and thus require an intervention on our side on each update to explicitly white-list said libraries.

Please just consider adding a LICENSE file to the top-level directory. You'll find the template here and only need to update the year and the name of the author or organization:
https://spdx.org/licenses/MIT.html

Thanks in advance

**Comment by rc1cent** [comment]
Hi.
Is there any chance to get the license text?
It would be great if the license was also in the npm package, so the license collecting tool can get the license text and put it into the Software Bill of Materials file/page of the product that uses this npm package.
Having license file is very important, especially in big products that use hundreds of third party components.

Thanks in advance.
